#!/bin/bash

TIMEOUT=15
QUIET=0

echoerr() {
  if [ "$QUIET" -ne 1 ]; then printf "%s\n" "$*" 1>&2; fi
}

usage() {
  exitcode="$1"
  cat << USAGE >&2
Usage:
  $cmdname host:port [-t timeout] [-- command args]
  -q | --quiet                        Do not output any status messages
  -t TIMEOUT | --timeout=timeout      Timeout in seconds, zero for no timeout
  -- COMMAND ARGS                     Execute command with args after the test finishes
USAGE
  exit "$exitcode"
}

wait_for() {
  command="$*"
  result=0
  for i in `seq $TIMEOUT` ; do
    for link in ${DEPENDS[@]} ; do
      HOST=$(printf "%s\n" "$link"| cut -d : -f 1)
      PORT=$(printf "%s\n" "$link"| cut -d : -f 2)
      
      echo "Checking $HOST:$PORT..."
      nc -z "$HOST" "$PORT" > /dev/null 2>&1
      result=$(expr $result + $?)
      echo "result=$result"
    done

    if [ $result -eq 0 ] ; then
      if [ -n "$command" ] ; then
        exec $command
      fi
      exit 0
    fi
    sleep 1
  done
  echo "Operation timed out" >&2
  exit 1
}

DEPENDS=()

while [ $# -gt 0 ]
do
  case "$1" in
    *:* )
    DEPENDS+=($1)
    # HOST=$(printf "%s\n" "$1"| cut -d : -f 1)
    # PORT=$(printf "%s\n" "$1"| cut -d : -f 2)
    shift 1
    ;;
    -q | --quiet)
    QUIET=1
    shift 1
    ;;
    -t)
    TIMEOUT="$2"
    if [ "$TIMEOUT" = "" ]; then break; fi
    shift 2
    ;;
    --timeout=*)
    TIMEOUT="${1#*=}"
    shift 1
    ;;
    --)
    shift
    break
    ;;
    --help)
    usage 0
    ;;
    *)
    echoerr "Unknown argument: $1"
    usage 1
    ;;
  esac
done

if [ ${#DEPENDS[@]} -eq 0 ]; then
  echoerr "Error: you need to provide a host and port to test."
  usage 2
fi

echo DEPENDS=${DEPENDS[@]}

wait_for "$@"
